/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.karengryg;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Movie extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -758785755945028824L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Movie\",\"namespace\":\"io.karengryg\",\"fields\":[{\"name\":\"movie_name\",\"type\":\"string\",\"doc\":\"Name of Movie\"},{\"name\":\"genre\",\"type\":\"string\",\"doc\":\"Genre of Movie\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Movie> ENCODER =
      new BinaryMessageEncoder<Movie>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Movie> DECODER =
      new BinaryMessageDecoder<Movie>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Movie> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Movie> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Movie>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Movie to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Movie from a ByteBuffer. */
  public static Movie fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Name of Movie */
  @Deprecated public java.lang.CharSequence movie_name;
  /** Genre of Movie */
  @Deprecated public java.lang.CharSequence genre;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Movie() {}

  /**
   * All-args constructor.
   * @param movie_name Name of Movie
   * @param genre Genre of Movie
   */
  public Movie(java.lang.CharSequence movie_name, java.lang.CharSequence genre) {
    this.movie_name = movie_name;
    this.genre = genre;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return movie_name;
    case 1: return genre;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: movie_name = (java.lang.CharSequence)value$; break;
    case 1: genre = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'movie_name' field.
   * @return Name of Movie
   */
  public java.lang.CharSequence getMovieName() {
    return movie_name;
  }

  /**
   * Sets the value of the 'movie_name' field.
   * Name of Movie
   * @param value the value to set.
   */
  public void setMovieName(java.lang.CharSequence value) {
    this.movie_name = value;
  }

  /**
   * Gets the value of the 'genre' field.
   * @return Genre of Movie
   */
  public java.lang.CharSequence getGenre() {
    return genre;
  }

  /**
   * Sets the value of the 'genre' field.
   * Genre of Movie
   * @param value the value to set.
   */
  public void setGenre(java.lang.CharSequence value) {
    this.genre = value;
  }

  /**
   * Creates a new Movie RecordBuilder.
   * @return A new Movie RecordBuilder
   */
  public static io.karengryg.Movie.Builder newBuilder() {
    return new io.karengryg.Movie.Builder();
  }

  /**
   * Creates a new Movie RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Movie RecordBuilder
   */
  public static io.karengryg.Movie.Builder newBuilder(io.karengryg.Movie.Builder other) {
    return new io.karengryg.Movie.Builder(other);
  }

  /**
   * Creates a new Movie RecordBuilder by copying an existing Movie instance.
   * @param other The existing instance to copy.
   * @return A new Movie RecordBuilder
   */
  public static io.karengryg.Movie.Builder newBuilder(io.karengryg.Movie other) {
    return new io.karengryg.Movie.Builder(other);
  }

  /**
   * RecordBuilder for Movie instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Movie>
    implements org.apache.avro.data.RecordBuilder<Movie> {

    /** Name of Movie */
    private java.lang.CharSequence movie_name;
    /** Genre of Movie */
    private java.lang.CharSequence genre;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.karengryg.Movie.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.movie_name)) {
        this.movie_name = data().deepCopy(fields()[0].schema(), other.movie_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.genre)) {
        this.genre = data().deepCopy(fields()[1].schema(), other.genre);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Movie instance
     * @param other The existing instance to copy.
     */
    private Builder(io.karengryg.Movie other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.movie_name)) {
        this.movie_name = data().deepCopy(fields()[0].schema(), other.movie_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.genre)) {
        this.genre = data().deepCopy(fields()[1].schema(), other.genre);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'movie_name' field.
      * Name of Movie
      * @return The value.
      */
    public java.lang.CharSequence getMovieName() {
      return movie_name;
    }

    /**
      * Sets the value of the 'movie_name' field.
      * Name of Movie
      * @param value The value of 'movie_name'.
      * @return This builder.
      */
    public io.karengryg.Movie.Builder setMovieName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.movie_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'movie_name' field has been set.
      * Name of Movie
      * @return True if the 'movie_name' field has been set, false otherwise.
      */
    public boolean hasMovieName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'movie_name' field.
      * Name of Movie
      * @return This builder.
      */
    public io.karengryg.Movie.Builder clearMovieName() {
      movie_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'genre' field.
      * Genre of Movie
      * @return The value.
      */
    public java.lang.CharSequence getGenre() {
      return genre;
    }

    /**
      * Sets the value of the 'genre' field.
      * Genre of Movie
      * @param value The value of 'genre'.
      * @return This builder.
      */
    public io.karengryg.Movie.Builder setGenre(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.genre = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'genre' field has been set.
      * Genre of Movie
      * @return True if the 'genre' field has been set, false otherwise.
      */
    public boolean hasGenre() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'genre' field.
      * Genre of Movie
      * @return This builder.
      */
    public io.karengryg.Movie.Builder clearGenre() {
      genre = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Movie build() {
      try {
        Movie record = new Movie();
        record.movie_name = fieldSetFlags()[0] ? this.movie_name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.genre = fieldSetFlags()[1] ? this.genre : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Movie>
    WRITER$ = (org.apache.avro.io.DatumWriter<Movie>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Movie>
    READER$ = (org.apache.avro.io.DatumReader<Movie>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
